// <auto-generated />
namespace YUMMY.Net.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migimageurl2addedtoabout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migimageurl2addedtoabout));
        
        string IMigrationMetadata.Id
        {
            get { return "202412171814081_mig-imageurl2-added-to-about"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
